### ISSUE TITLE
Error when trying to find carriageway and position from point coordinates

### ISSUE THREAD

**Issue by Winda2** [johnbullnz/pyramm#31]
Used the pyramm example to retrieve the position:
```
centreline = conn.centreline()
point = Point((172.618567, -43.441594))  # Shapely Point object
position = centreline.position(point, point_crs=4326)
```

This resulted in this error:

```
    raise NotImplementedError(
NotImplementedError: Multi-part geometries do not provide a coordinate sequence
```

Attributed to the conn.centreline()

**Comment by johnbullnz** [comment]
@Winda2 please try the latest version of *pyramm* (v1.22) and see if you still have this issue.

**Comment by johnbullnz** [comment]
Closing as unable to reproduce. Please open a new issue if the problem persists.
